zfs: Minor script improvements

diff --git a/zfs/templates/main/zfs_scrub-pools.sh.j2 b/zfs/templates/main/zfs_scrub-pools.sh.j2
--- a/zfs/templates/main/zfs_scrub-pools.sh.j2
+++ b/zfs/templates/main/zfs_scrub-pools.sh.j2
@@ -37,32 +37,32 @@ PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 # COMMANDS
 #-------------------------------------------------------------------------------
 
-which='/usr/bin/which' && [ -x $which ] || exit 0100
-basename=$($which basename) || exit 0101
-date=$($which date) || exit 0102
-echo=$($which echo) || exit 0103
-expr=$($which expr) || exit 0104
-grep=$($which grep) || exit 0105
-hostname=$($which hostname) || exit 0106
-logger=$($which logger) || exit 0107
+which='/usr/bin/which' && [ -x $which ] || exit 1100
+basename=$($which basename) || exit 1101
+date=$($which date) || exit 1102
+echo=$($which echo) || exit 1103
+expr=$($which expr) || exit 1104
+grep=$($which grep) || exit 1105
+hostname=$($which hostname) || exit 1106
+logger=$($which logger) || exit 1107
 {% if (zfs_monitor_mail_state is defined) and ((zfs_monitor_mail_state == 'true') or (zfs_monitor_mail_state == 'yes') or (zfs_monitor_mail_state == 'enable')) %}
-mailx=$($which mailx) || exit 0108
+mailx=$($which mailx) || exit 1108
 {% endif %}
-rm=$($which rm) || exit 0109
-sleep=$($which sleep) || exit 0110
-touch=$($which touch) || exit 0111
-whoami=$($which whoami) || exit 0112
-zpool=$($which zpool) || exit 0113
+rm=$($which rm) || exit 1109
+sleep=$($which sleep) || exit 1110
+touch=$($which touch) || exit 1111
+whoami=$($which whoami) || exit 1112
+zpool=$($which zpool) || exit 1113
 
 #-------------------------------------------------------------------------------
 # VARIABLES
 #-------------------------------------------------------------------------------
 
 # Get the short host name
-host=$($hostname -s) || exit 0200
+host=$($hostname -s) || exit 1200
 
 # Get the script name and PID
-script="$($basename $0)[$$]" || exit 0201
+script="$($basename $0)[$$]" || exit 1201
 
 # Get the start date and time
 date_start=$($date '+%Y-%m-%dT%H:%M:%S%z')
@@ -192,7 +192,7 @@ log_and_exit_on_error() {
   code=$2
   severity=$3
   message=$4
-  if [ $retval -ne 0 ] ; then
+  if [ $retval -ne 0 ]; then
     $rm -f $lockfile
     $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
     $logger -t $script "$severity: $message Code: $code"
@@ -211,7 +211,7 @@ watch_and_wait_on_change() {
   time_step=$4
   time_maximum=$5
   while ${watch_key} | $grep ${watch_option} "${watch_value}" > /dev/null 2>&1 ; do
-    if [ $time_initial -lt $time_maximum ] ; then
+    if [ $time_initial -lt $time_maximum ]; then
       time_initial=$($expr $time_initial + $time_step)
       $sleep $time_initial
     else
@@ -225,8 +225,8 @@ watch_and_wait_on_change() {
 #-------------------------------------------------------------------------------
 
 # Check if script is running as correct user
-if [ "$($whoami)" != "$user" ] ; then
-  code='0300'
+if [ "$($whoami)" != "$user" ]; then
+  code='1300'
   severity='Error'
   message="Please run script as user '$user'"
   $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
@@ -238,10 +238,10 @@ fi
 #-------------------------------------------------------------------------------
 
 # Create lockfile
-if [ ! -e $lockfile ] ; then
-  $touch $lockfile || log_and_exit_on_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
+if [ ! -e $lockfile ]; then
+  $touch $lockfile || log_and_exit_on_error "$?" '1400' 'Warning' 'Could not create lockfile. Please investigate.'
 else
-  log_and_exit_on_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
+  log_and_exit_on_error "$?" '1401' 'Warning' 'Lockfile does already exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -256,7 +256,7 @@ for pool in $zfs_pools ; do
 
   # Scrub next ZFS pool
   $zpool scrub $pool
-  log_and_exit_on_error "$?" '0500' 'Error' "Unable to scrub ZFS pool: '$pool'"
+  log_and_exit_on_error "$?" '1500' 'Error' "Unable to scrub ZFS pool: '$pool'"
 done
 
 # Check ZFS pools
@@ -267,11 +267,11 @@ for pool in $zfs_pools ; do
 
   # Get next ZFS pool status
   zfs_pool_status="$($zpool status -xv $pool)"
-  log_and_exit_on_error "$?" '0501' 'Error' "Unable to get ZFS pool status: '$pool'"
+  log_and_exit_on_error "$?" '1501' 'Error' "Unable to get ZFS pool status: '$pool'"
 
   # Check next ZFS pool status
   echo "$zfs_pool_status" | $grep 'healthy' > /dev/null 2>&1
-  log_and_exit_on_error "$?" '0502' 'Critical' "ZFS pool is unhealthy: '$pool'"
+  log_and_exit_on_error "$?" '1502' 'Critical' "ZFS pool is unhealthy: '$pool'"
 done
 
 #-------------------------------------------------------------------------------
@@ -279,10 +279,10 @@ done
 #-------------------------------------------------------------------------------
 
 # Delete lockfile
-if [ -e $lockfile ] ; then
-  $rm -f $lockfile || log_and_exit_on_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
+if [ -e $lockfile ]; then
+  $rm -f $lockfile || log_and_exit_on_error "$?" '1402' 'Warning' 'Could not delete lockfile. Please investigate.'
 else
-  log_and_exit_on_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
+  log_and_exit_on_error "$?" '1403' 'Warning' 'Lockfile did not exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
