zfs: E: Improve Shell script to prevent globbing and word splitting

diff --git a/zfs/templates/main/zfs_scrub-pools.sh.j2 b/zfs/templates/main/zfs_scrub-pools.sh.j2
--- a/zfs/templates/main/zfs_scrub-pools.sh.j2
+++ b/zfs/templates/main/zfs_scrub-pools.sh.j2
@@ -51,7 +51,6 @@ zpool=$(${which} zpool) || { echo "Error: Command 'zpool' not found."; exit 127;
 
 host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
 script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-date_start=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
 time_start=$(${date} '+%s')
 user='{{file_owner_zfs_scrub_pools_sh}}'
 lockfile='{{file_dst_zfs_script_dir}}/zfs_scrub-pools.lock'
@@ -116,12 +115,12 @@ watch_and_wait_for_change() {
   watch_option=$3
   time_step=$4
   time_maximum=$5
-  while ${watch_key} | ${grep} ${watch_option} "${watch_value}" > /dev/null 2>&1 ; do
-    if [ ${time_initial} -lt ${time_maximum} ]; then
-      time_initial=$(${expr} ${time_initial} + ${time_step})
-      ${sleep} ${time_initial}
+  while ${watch_key} | ${grep} "${watch_option}" "${watch_value}" > /dev/null 2>&1 ; do
+    if [ "${time_initial}" -lt "${time_maximum}" ]; then
+      time_initial=$(${expr} "${time_initial}" + "${time_step}")
+      ${sleep} "${time_initial}"
     else
-      ${sleep} ${time_initial}
+      ${sleep} "${time_initial}"
     fi
   done
 }
@@ -131,22 +130,22 @@ check_script_user() {
     retval=77
     severity='Error'
     message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    exit ${retval}
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    exit "${retval}"
   fi
 }
 
 create_lockfile() {
-  if [ ! -e ${lockfile} ]; then
-    ${touch} ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  if [ ! -e "${lockfile}" ]; then
+    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
   fi
 }
 
 remove_lockfile() {
-  if [ -e ${lockfile} ]; then
-    ${rm} -f ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+  if [ -e "${lockfile}" ]; then
+    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
   fi
@@ -156,29 +155,28 @@ log_and_exit_on_error() {
   retval=$1
   severity=$2
   message=$3
-  if [ ${retval} -ne 0 ]; then
-    ${rm} -f ${lockfile}
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    ${logger} -t ${script} "${severity}: ${message}"
+  if [ "${retval}" -ne 0 ]; then
+    ${rm} -f "${lockfile}"
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    ${logger} -t "${script}" "${severity}: ${message}"
 {% if (zfs_monitor_mail_state is match('true|yes|enable')) %}
-    mail_error ${retval} "${severity}" "${message}"
+    mail_error "${retval}" "${severity}" "${message}"
 {% endif %}
-    exit ${retval}
+    exit "${retval}"
   fi
 }
 
 log_and_exit() {
-  date_end=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
   time_end=$(${date} '+%s')
-  time_exec=$(${expr} ${time_end} - ${time_start})
+  time_exec=$(${expr} "${time_end}" - "${time_start}")
   time_hr=$(${date} -u -r "${time_exec}" '+%H:%M:%S')
 
   retval=0
   severity='Info'
   message='All ZFS pools are healthy.'
-  ${logger} -t ${script} "${severity}: ${message} Duration: ${time_hr}"
+  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
 
-  exit ${retval}
+  exit "${retval}"
 }
 
 #-------------------------------------------------------------------------------
