ansible: Minor script improvements

diff --git a/ansible/templates/main/ansible_run-playbook.sh.j2 b/ansible/templates/main/ansible_run-playbook.sh.j2
--- a/ansible/templates/main/ansible_run-playbook.sh.j2
+++ b/ansible/templates/main/ansible_run-playbook.sh.j2
@@ -37,31 +37,31 @@ PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 # COMMANDS
 #-------------------------------------------------------------------------------
 
-which='/usr/bin/which' && [ -x $which ] || exit 0100
-basename=$($which basename) || exit 0101
-chmod=$($which chmod) || exit 0102
-find=$($which find) || exit 0103
-date=$($which date) || exit 0104
-echo=$($which echo) || exit 0105
-expr=$($which expr) || exit 0106
-hostname=$($which hostname) || exit 0107
-logger=$($which logger) || exit 0108
+which='/usr/bin/which' && [ -x $which ] || exit 1100
+basename=$($which basename) || exit 1101
+chmod=$($which chmod) || exit 1102
+find=$($which find) || exit 1103
+date=$($which date) || exit 1104
+echo=$($which echo) || exit 1105
+expr=$($which expr) || exit 1106
+hostname=$($which hostname) || exit 1107
+logger=$($which logger) || exit 1108
 {% if (ansible_monitor_mail_state is defined) and ((ansible_monitor_mail_state == 'true') or (ansible_monitor_mail_state == 'yes') or (ansible_monitor_mail_state == 'enable')) %}
-mailx=$($which mailx) || exit 0109
+mailx=$($which mailx) || exit 1109
 {% endif %}
-rm=$($which rm) || exit 0110
-touch=$($which touch) || exit 0111
-whoami=$($which whoami) || exit 0112
+rm=$($which rm) || exit 1110
+touch=$($which touch) || exit 1111
+whoami=$($which whoami) || exit 1112
 
 #-------------------------------------------------------------------------------
 # VARIABLES
 #-------------------------------------------------------------------------------
 
 # Get the short host name
-host=$($hostname -s) || exit 0200
+host=$($hostname -s) || exit 1200
 
 # Get the script name and PID
-script="$($basename $0)[$$]" || exit 0201
+script="$($basename $0)[$$]" || exit 1201
 
 # Get the start date and time
 date_start=$($date '+%Y-%m-%dT%H:%M:%S%z')
@@ -221,7 +221,7 @@ log_and_exit_on_error() {
   code=$2
   severity=$3
   message=$4
-  if [ $retval -ne 0 ] ; then
+  if [ $retval -ne 0 ]; then
     $rm -f $lockfile
     $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
     $logger -t $script "$severity: $message Code: $code"
@@ -237,8 +237,8 @@ log_and_exit_on_error() {
 #-------------------------------------------------------------------------------
 
 # Check if script is running as correct user
-if [ "$($whoami)" != "$user" ] ; then
-  code='0300'
+if [ "$($whoami)" != "$user" ]; then
+  code='1300'
   severity='Error'
   message="Please run script as user '$user'"
   $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
@@ -250,10 +250,10 @@ fi
 #-------------------------------------------------------------------------------
 
 # Create lockfile
-if [ ! -e $lockfile ] ; then
-  $touch $lockfile || log_and_exit_on_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
+if [ ! -e $lockfile ]; then
+  $touch $lockfile || log_and_exit_on_error "$?" '1400' 'Warning' 'Could not create lockfile. Please investigate.'
 else
-  log_and_exit_on_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
+  log_and_exit_on_error "$?" '1401' 'Warning' 'Lockfile does already exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -261,17 +261,17 @@ fi
 #-------------------------------------------------------------------------------
 
 # Check if Ansible 'env-setup' file exist
-if [ ! -e ${ansible_dir}/hacking/env-setup ] ; then
-  log_and_exit_on_error "$?" '0500' 'Error' "Ansible 'env-setup' file does not exist."
+if [ ! -e ${ansible_dir}/hacking/env-setup ]; then
+  log_and_exit_on_error "$?" '1500' 'Error' "Ansible 'env-setup' file does not exist."
 fi
 
 # Load Ansible environment variables
 source ${ansible_dir}/hacking/env-setup > /dev/null 2>&1
-log_and_exit_on_error "$?" '0501' 'Error' 'Unable to load Ansible environment variables.'
+log_and_exit_on_error "$?" '1501' 'Error' 'Unable to load Ansible environment variables.'
 
 # Check if Ansible 'ansible-playbook' command is available
 ansible_playbook=$($which ansible-playbook)
-log_and_exit_on_error "$?" '0502' 'Error' "Ansible 'ansible-playbook' command is not available."
+log_and_exit_on_error "$?" '1502' 'Error' "Ansible 'ansible-playbook' command is not available."
 
 # Insert Ansible log header
 $echo "--------------------------------------------------------------------------------
@@ -287,11 +287,11 @@ FQDN        : {{ansible_fqdn}}
 
 --------------------------------------------------------------------------------
 " > "${log_dir}/ansible_${exec_date}.log"
-log_and_exit_on_error "$?" '0503' 'Error' 'Unable to insert Ansible log header.'
+log_and_exit_on_error "$?" '1503' 'Error' 'Unable to insert Ansible log header.'
 
 # Ensure proper file permission
 $find $log_dir -type f -name "ansible_${exec_date}.log" -exec $chmod $log_mode '{}' ';'
-log_and_exit_on_error "$?" '0504' 'Error' 'Unable to ensure proper file permission.'
+log_and_exit_on_error "$?" '1504' 'Error' 'Unable to ensure proper file permission.'
 
 # Run Ansible playbooks
 for playbook in $playbooks ; do
@@ -301,15 +301,15 @@ for playbook in $playbooks ; do
 PLAYBOOK ($playbook) - BEGIN
 --------------------------------------------------------------------------------
 " >> "${log_dir}/ansible_${exec_date}.log"
-  log_and_exit_on_error "$?" '0505' 'Error' "Unable to insert playbook 'begin' tag."
+  log_and_exit_on_error "$?" '1505' 'Error' "Unable to insert playbook 'begin' tag."
 
   $ansible_playbook -i ${playbooks_dir}/${playbook}/hosts ${playbooks_dir}/${playbook}/site.yml --user=ansible --sudo >> "${log_dir}/ansible_${exec_date}.log" 2>&1
-  if [ "$?" -eq '0' ] ; then
+  if [ "$?" -eq '0' ]; then
     severity='Info'
     message="Ansible playbook '$playbook' executed."
     $logger -t $script "$severity: $message"
   else
-    log_and_exit_on_error "$?" '0506' 'Error' "Unable to run Ansible playbook '$playbook'"
+    log_and_exit_on_error "$?" '1506' 'Error' "Unable to run Ansible playbook '$playbook'"
   fi
   # Insert playbook 'end' tag
   $echo "
@@ -317,22 +317,22 @@ PLAYBOOK ($playbook) - BEGIN
 PLAYBOOK ($playbook) - END
 --------------------------------------------------------------------------------
 " >> "${log_dir}/ansible_${exec_date}.log"
-  log_and_exit_on_error "$?" '0507' 'Error' "Unable to insert playbook 'end' tag."
+  log_and_exit_on_error "$?" '1507' 'Error' "Unable to insert playbook 'end' tag."
 done
 
 # Remove old Ansible log files
 $find $log_dir -type f -name "ansible_*.log" -mtime +$purge_period -exec $rm -f '{}' ';'
-log_and_exit_on_error "$?" '0508' 'Error' 'Unable to remove old Ansible log files.'
+log_and_exit_on_error "$?" '1508' 'Error' 'Unable to remove old Ansible log files.'
 
 #-------------------------------------------------------------------------------
 # LOCKFILE
 #-------------------------------------------------------------------------------
 
 # Delete lockfile
-if [ -e $lockfile ] ; then
-  $rm -f $lockfile || log_and_exit_on_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
+if [ -e $lockfile ]; then
+  $rm -f $lockfile || log_and_exit_on_error "$?" '1402' 'Warning' 'Could not delete lockfile. Please investigate.'
 else
-  log_and_exit_on_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
+  log_and_exit_on_error "$?" '1403' 'Warning' 'Lockfile did not exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
