ansible: Improve Ansible playbook script

diff --git a/ansible/templates/main/ansible_run-playbook.sh.j2 b/ansible/templates/main/ansible_run-playbook.sh.j2
--- a/ansible/templates/main/ansible_run-playbook.sh.j2
+++ b/ansible/templates/main/ansible_run-playbook.sh.j2
@@ -134,7 +134,7 @@ mail_subject='{% if (ansible_monitor_mail_subject is defined) and not ((ansible_
 
 {% if (ansible_monitor_mail_state is defined) and ((ansible_monitor_mail_state == 'true') or (ansible_monitor_mail_state == 'yes') or (ansible_monitor_mail_state == 'enable')) %}
 # Mail monitoring
-mail_error () {
+mail_error() {
   retval=$1
   code=$2
   severity=$3
@@ -198,15 +198,15 @@ Subject     : $mail_subject"
 {% endif %}
 
 # Log and exit if return value is not equal zero
-log_and_exit_on_error () {
+log_and_exit_on_error() {
   retval=$1
   code=$2
   severity=$3
   message=$4
-  if [ $retval -ne 0 ]; then
+  if [ $retval -ne 0 ] ; then
     $rm -f $lockfile
-    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $code - $message""
-    $logger -t $script "$severity: $code - $message"
+    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
+    $logger -t $script "$severity: $message Code: $code"
 {% if (ansible_monitor_mail_state is defined) and ((ansible_monitor_mail_state == 'true') or (ansible_monitor_mail_state == 'yes') or (ansible_monitor_mail_state == 'enable')) %}
     mail_error $retval $code "$severity" "$message"
 {% endif %}
@@ -219,11 +219,11 @@ log_and_exit_on_error () {
 #-------------------------------------------------------------------------------
 
 # Check if script is running as correct user
-if [ "$($whoami)" != "$user" ]; then
+if [ "$($whoami)" != "$user" ] ; then
   code='0300'
   severity='Error'
   message="Please run script as user '$user'"
-  $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity "($code)": $message""
+  $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
   exit $code
 fi
 
@@ -232,7 +232,7 @@ fi
 #-------------------------------------------------------------------------------
 
 # Create lockfile
-if [ ! -e $lockfile ]; then
+if [ ! -e $lockfile ] ; then
   $touch $lockfile || log_and_exit_on_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
 else
   log_and_exit_on_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
@@ -243,7 +243,7 @@ fi
 #-------------------------------------------------------------------------------
 
 # Check if Ansible 'env-setup' file exist
-if [ ! -e ${ansible_dir}/hacking/env-setup ]; then
+if [ ! -e ${ansible_dir}/hacking/env-setup ] ; then
   log_and_exit_on_error "$?" '0500' 'Error' "Ansible 'env-setup' file does not exist."
 fi
 
@@ -286,12 +286,12 @@ PLAYBOOK ($playbook) - BEGIN
   log_and_exit_on_error "$?" '0505' 'Error' "Unable to insert playbook 'begin' tag."
 
   $ansible_playbook -i ${playbooks_dir}/${playbook}/hosts ${playbooks_dir}/${playbook}/site.yml --user=ansible --sudo >> "${log_dir}/ansible_${exec_date}.log" 2>&1
-  if [ "$?" -eq '0' ]; then
+  if [ "$?" -eq '0' ] ; then
     severity='Info'
     message="Ansible playbook '$playbook' executed."
     $logger -t $script "$severity: $message"
   else
-    log_and_exit_on_error "$?" '0506' 'Error' "Unable to run Ansible playbook '$playbook'."
+    log_and_exit_on_error "$?" '0506' 'Error' "Unable to run Ansible playbook '$playbook'"
   fi
   # Insert playbook 'end' tag
   $echo "
@@ -311,7 +311,7 @@ log_and_exit_on_error "$?" '0508' 'Error' 'Unable to remove old Ansible log file
 #-------------------------------------------------------------------------------
 
 # Delete lockfile
-if [ -e $lockfile ]; then
+if [ -e $lockfile ] ; then
   $rm -f $lockfile || log_and_exit_on_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
 else
   log_and_exit_on_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
@@ -342,7 +342,6 @@ retval=0
 code='0000'
 severity='Info'
 message='All Ansible playbooks executed.'
-$logger -t $script "$severity: $message"
-$logger -t $script "Duration: $time_hr"
+$logger -t $script "$severity: $message Duration: $time_hr"
 
 exit $retval
