ansible: Minor script improvement

diff --git a/ansible/templates/main/ansible_run-playbook.sh.j2 b/ansible/templates/main/ansible_run-playbook.sh.j2
--- a/ansible/templates/main/ansible_run-playbook.sh.j2
+++ b/ansible/templates/main/ansible_run-playbook.sh.j2
@@ -198,7 +198,7 @@ Subject     : $mail_subject"
 {% endif %}
 
 # Log and exit if return value is not equal zero
-log_and_exit_if_error () {
+log_and_exit_on_error () {
   retval=$1
   code=$2
   severity=$3
@@ -233,9 +233,9 @@ fi
 
 # Create lockfile
 if [ ! -e $lockfile ]; then
-  $touch $lockfile || log_and_exit_if_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
+  $touch $lockfile || log_and_exit_on_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
 else
-  log_and_exit_if_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
+  log_and_exit_on_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -244,16 +244,16 @@ fi
 
 # Check if Ansible 'env-setup' file exist
 if [ ! -e ${ansible_dir}/hacking/env-setup ]; then
-  log_and_exit_if_error "$?" '0500' 'Error' "Ansible 'env-setup' file does not exist."
+  log_and_exit_on_error "$?" '0500' 'Error' "Ansible 'env-setup' file does not exist."
 fi
 
 # Load Ansible environment variables
 source ${ansible_dir}/hacking/env-setup > /dev/null 2>&1
-log_and_exit_if_error "$?" '0501' 'Error' 'Unable to load Ansible environment variables.'
+log_and_exit_on_error "$?" '0501' 'Error' 'Unable to load Ansible environment variables.'
 
 # Check if Ansible 'ansible-playbook' command is available
 ansible_playbook=$($which ansible-playbook)
-log_and_exit_if_error "$?" '0502' 'Error' "Ansible 'ansible-playbook' command is not available."
+log_and_exit_on_error "$?" '0502' 'Error' "Ansible 'ansible-playbook' command is not available."
 
 # Insert Ansible log header
 $echo "--------------------------------------------------------------------------------
@@ -269,11 +269,11 @@ FQDN        : {{ansible_fqdn}}
 
 --------------------------------------------------------------------------------
 " > "${log_dir}/ansible_${exec_date}.log"
-log_and_exit_if_error "$?" '0503' 'Error' 'Unable to insert Ansible log header.'
+log_and_exit_on_error "$?" '0503' 'Error' 'Unable to insert Ansible log header.'
 
 # Ensure proper file permission
 $find $log_dir -type f -name "ansible_${exec_date}.log" -exec $chmod $log_mode '{}' ';'
-log_and_exit_if_error "$?" '0504' 'Error' 'Unable to ensure proper file permission.'
+log_and_exit_on_error "$?" '0504' 'Error' 'Unable to ensure proper file permission.'
 
 # Run Ansible playbooks
 for playbook in $playbooks ; do
@@ -283,7 +283,7 @@ for playbook in $playbooks ; do
 PLAYBOOK ($playbook) - BEGIN
 --------------------------------------------------------------------------------
 " >> "${log_dir}/ansible_${exec_date}.log"
-  log_and_exit_if_error "$?" '0505' 'Error' "Unable to insert playbook 'begin' tag."
+  log_and_exit_on_error "$?" '0505' 'Error' "Unable to insert playbook 'begin' tag."
 
   $ansible_playbook -i ${playbooks_dir}/${playbook}/hosts ${playbooks_dir}/${playbook}/site.yml --user=ansible --sudo >> "${log_dir}/ansible_${exec_date}.log" 2>&1
   if [ "$?" -eq '0' ]; then
@@ -291,7 +291,7 @@ PLAYBOOK ($playbook) - BEGIN
     message="Ansible playbook '$playbook' executed."
     $logger -t $script "$severity: $message"
   else
-    log_and_exit_if_error "$?" '0506' 'Error' "Unable to run Ansible playbook '$playbook'."
+    log_and_exit_on_error "$?" '0506' 'Error' "Unable to run Ansible playbook '$playbook'."
   fi
   # Insert playbook 'end' tag
   $echo "
@@ -299,12 +299,12 @@ PLAYBOOK ($playbook) - BEGIN
 PLAYBOOK ($playbook) - END
 --------------------------------------------------------------------------------
 " >> "${log_dir}/ansible_${exec_date}.log"
-  log_and_exit_if_error "$?" '0507' 'Error' "Unable to insert playbook 'end' tag."
+  log_and_exit_on_error "$?" '0507' 'Error' "Unable to insert playbook 'end' tag."
 done
 
 # Remove old Ansible log files
 $find $log_dir -type f -name "ansible_*.log" -mtime +$purge_period -exec $rm -f '{}' ';'
-log_and_exit_if_error "$?" '0508' 'Error' 'Unable to remove old Ansible log files.'
+log_and_exit_on_error "$?" '0508' 'Error' 'Unable to remove old Ansible log files.'
 
 #-------------------------------------------------------------------------------
 # LOCKFILE
@@ -312,9 +312,9 @@ log_and_exit_if_error "$?" '0508' 'Error' 'Unable to remove old Ansible log file
 
 # Delete lockfile
 if [ -e $lockfile ]; then
-  $rm -f $lockfile || log_and_exit_if_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
+  $rm -f $lockfile || log_and_exit_on_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
 else
-  log_and_exit_if_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
+  log_and_exit_on_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
