ntpd: I: Shell script improvements

diff --git a/ntpd/templates/main/ntpd_update-time.sh.j2 b/ntpd/templates/main/ntpd_update-time.sh.j2
--- a/ntpd/templates/main/ntpd_update-time.sh.j2
+++ b/ntpd/templates/main/ntpd_update-time.sh.j2
@@ -28,19 +28,19 @@ PATH='/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin'
 # COMMANDS
 #-------------------------------------------------------------------------------
 
-which='/usr/bin/which' && [ -x $which ] || { echo "Error: Command 'which' not found."; exit 127; }
-basename=$($which basename) || { echo "Error: Command 'basename' not found."; exit 127; }
-date=$($which date) || { echo "Error: Command 'date' not found."; exit 127; }
-echo=$($which echo) || { echo "Error: Command 'echo' not found."; exit 127; }
-expr=$($which expr) || { echo "Error: Command 'expr' not found."; exit 127; }
-hostname=$($which hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
-logger=$($which logger) || { echo "Error: Command 'logger' not found."; exit 127; }
+which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
+basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
+echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
 {% if (ntpd_monitor_mail_state is match('true|yes|enable')) %}
-mailx=$($which mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
+mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
-rm=$($which rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-touch=$($which touch) || { echo "Error: Command 'touch' not found."; exit 127; }
-whoami=$($which whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
 ntpd='{{ntpd}}'
 
@@ -48,10 +48,10 @@ ntpd='{{ntpd}}'
 # VARIABLES
 #-------------------------------------------------------------------------------
 
-host=$($hostname -s) || { echo "Error: Host name unknown."; exit 68; }
-script="$($basename $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-date_start=$($date '+%Y-%m-%dT%H:%M:%S%z')
-time_start=$($date '+%s')
+host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
+script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+date_start=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
+time_start=$(${date} '+%s')
 user='{{file_owner_ntpd_update_time_sh}}'
 lockfile='{{file_path_ntpd_script_dir}}/ntpd_update-time.lock'
 retval=0
@@ -79,9 +79,9 @@ mail_error() {
 ERROR
 --------------------------------------------------------------------------------
 
-Message     : $message
-Severity    : $severity
-Date & Time : $($date '+%Y-%m-%dT%H:%M:%S%z')
+Message     : ${message}
+Severity    : ${severity}
+Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
 
 --------------------------------------------------------------------------------
 SCRIPT
@@ -102,39 +102,39 @@ FQDN        : {{ansible_fqdn}}
 MAIL
 --------------------------------------------------------------------------------
 
-Sender      : $mail_sender
-Recipient   : $mail_recipient
-Subject     : $mail_subject"
+Sender      : ${mail_sender}
+Recipient   : ${mail_recipient}
+Subject     : ${mail_subject}"
 
 {% if (ansible_os_family == 'FreeBSD') %}
-  $echo "$mail_body" | $mailx -s "$mail_subject" -F "$mail_recipient" > /dev/null 2>&1
+  ${echo} "${mail_body}" | ${mailx} -s "${mail_subject}" -F "${mail_recipient}" > /dev/null 2>&1
 {% else %}
-  $echo "$mail_body" | $mailx -a "From: "$mail_sender"" -s "$mail_subject" "$mail_recipient" > /dev/null 2>&1
+  ${echo} "${mail_body}" | ${mailx} -a "From: "${mail_sender}"" -s "${mail_subject}" "${mail_recipient}" > /dev/null 2>&1
 {% endif %}
 }
 {% endif %}
 
 check_script_user() {
-  if [ "$($whoami)" != "$user" ]; then
+  if [ "$(${whoami})" != "${user}" ]; then
     retval=77
     severity='Error'
-    message="Please run script as user '$user'"
-    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message""
-    exit $retval
+    message="Please run script as user '${user}'"
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
+    exit ${retval}
   fi
 }
 
 create_lockfile() {
-  if [ ! -e $lockfile ]; then
-    $touch $lockfile || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  if [ ! -e ${lockfile} ]; then
+    ${touch} ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
   fi
 }
 
 remove_lockfile() {
-  if [ -e $lockfile ]; then
-    $rm -f $lockfile || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+  if [ -e ${lockfile} ]; then
+    ${rm} -f ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
   fi
@@ -144,29 +144,29 @@ log_and_exit_on_error() {
   retval=$1
   severity=$2
   message=$3
-  if [ $retval -ne 0 ]; then
-    $rm -f $lockfile
-    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message""
-    $logger -t $script "$severity: $message"
+  if [ ${retval} -ne 0 ]; then
+    ${rm} -f ${lockfile}
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "$[severity: ${message}""
+    ${logger} -t ${script} "${severity}: ${message}"
 {% if (ntpd_monitor_mail_state is match('true|yes|enable')) %}
-    mail_error $retval "$severity" "$message"
+    mail_error ${retval} "${severity}" "${message}"
 {% endif %}
-    exit $retval
+    exit ${retval}
   fi
 }
 
 log_and_exit() {
-  date_end=$($date '+%Y-%m-%dT%H:%M:%S%z')
-  time_end=$($date '+%s')
-  time_exec=$($expr $time_end - $time_start)
-  time_hr=$($date -u -r "$time_exec" '+%H:%M:%S')
+  date_end=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
+  time_end=$(${date} '+%s')
+  time_exec=$(${expr} ${time_end} - ${time_start})
+  time_hr=$(${date} -u -r "${time_exec}" '+%H:%M:%S')
 
   retval=0
   severity='Info'
   message='System time and hardware clock updated.'
-  $logger -t $script "$severity: $message Duration: $time_hr"
+  ${logger} -t ${script} "${severity}: ${message} Duration: ${time_hr}"
 
-  exit $retval
+  exit ${retval}
 }
 
 #-------------------------------------------------------------------------------
@@ -178,8 +178,8 @@ check_script_user
 create_lockfile
 
 # Update the system time by polling NTP servers to determine the correct time
-for ntpd_server in $ntpd_servers ; do
-  $ntpd $ntpd_server > /dev/null 2>&1
+for ntpd_server in ${ntpd_servers} ; do
+  ${ntpd} ${ntpd_server} > /dev/null 2>&1
   if [ $? -eq 0 ]; then
     ntpd_status=0
     break;
@@ -187,7 +187,7 @@ for ntpd_server in $ntpd_servers ; do
     ntpd_status=1
   fi
 done
-log_and_exit_on_error "$ntpd_status" 'Error' 'Unable to update the system time.'
+log_and_exit_on_error "${ntpd_status}" 'Error' 'Unable to update the system time.'
 
 remove_lockfile
 
