ntpd: B: Improve return value verification and fix unexpected operator/operand issue E: Improve Shell script to prevent globbing and word splitting

diff --git a/ntpd/templates/main/ntpd_update-time.sh.j2 b/ntpd/templates/main/ntpd_update-time.sh.j2
--- a/ntpd/templates/main/ntpd_update-time.sh.j2
+++ b/ntpd/templates/main/ntpd_update-time.sh.j2
@@ -50,7 +50,6 @@ ntpd='{{ntpd}}'
 
 host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
 script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-date_start=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
 time_start=$(${date} '+%s')
 user='{{file_owner_ntpd_update_time_sh}}'
 lockfile='{{file_dst_ntpd_script_dir}}/ntpd_update-time.lock'
@@ -111,22 +110,22 @@ check_script_user() {
     retval=77
     severity='Error'
     message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    exit ${retval}
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    exit "${retval}"
   fi
 }
 
 create_lockfile() {
-  if [ ! -e ${lockfile} ]; then
-    ${touch} ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  if [ ! -e "${lockfile}" ]; then
+    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
   fi
 }
 
 remove_lockfile() {
-  if [ -e ${lockfile} ]; then
-    ${rm} -f ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+  if [ -e "${lockfile}" ]; then
+    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
   fi
@@ -136,29 +135,27 @@ log_and_exit_on_error() {
   retval=$1
   severity=$2
   message=$3
-  if [ ${retval} -ne 0 ]; then
-    ${rm} -f ${lockfile}
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: "${severity}: ${message}""
-    ${logger} -t ${script} "${severity}: ${message}"
+  if [ "${retval}" -ne 0 ]; then
+    ${rm} -f "${lockfile}"
+    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
+    ${logger} -t "${script}" "${severity}: ${message}"
 {% if (ntpd_monitor_mail_state is match('true|yes|enable')) %}
-    mail_error ${retval} "${severity}" "${message}"
+    mail_error "${retval}" "${severity}" "${message}"
 {% endif %}
-    exit ${retval}
+    exit "${retval}"
   fi
 }
 
 log_and_exit() {
-  date_end=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
   time_end=$(${date} '+%s')
-  time_exec=$(${expr} ${time_end} - ${time_start})
+  time_exec=$(${expr} "${time_end}" - "${time_start}")
   time_hr=$(${date} -u -r "${time_exec}" '+%H:%M:%S')
 
   retval=0
   severity='Info'
   message='System time and hardware clock updated.'
-  ${logger} -t ${script} "${severity}: ${message} Duration: ${time_hr}"
-
-  exit ${retval}
+  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+  exit "${retval}"
 }
 
 #-------------------------------------------------------------------------------
@@ -171,8 +168,7 @@ create_lockfile
 
 # Update the system time by polling NTP servers
 for ntpd_server in ${ntpd_servers} ; do
-  ${ntpd} ${ntpd_server} > /dev/null 2>&1
-  if [ $? -eq 0 ]; then
+  if [ "$(${ntpd} ${ntpd_server} > /dev/null 2>&1)" -eq 0 ]; then
     ntpd_status=0
     break;
   else
