openntpd: E: Improve Shell script to prevent globbing and word splitting

diff --git a/openntpd/templates/main/openntpd_check-time.sh.j2 b/openntpd/templates/main/openntpd_check-time.sh.j2
--- a/openntpd/templates/main/openntpd_check-time.sh.j2
+++ b/openntpd/templates/main/openntpd_check-time.sh.j2
@@ -121,7 +121,7 @@ check_script_user() {
 
 create_lockfile() {
   if [ ! -e "${lockfile}" ]; then
-    ${touch} ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
   fi
@@ -129,7 +129,7 @@ create_lockfile() {
 
 remove_lockfile() {
   if [ -e "${lockfile}" ]; then
-    ${rm} -f ${lockfile} || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
   else
     log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
   fi
@@ -140,7 +140,7 @@ log_and_exit_on_error() {
   severity=$2
   message=$3
   if [ "${retval}" -ne 0 ]; then
-    ${rm} -f ${lockfile}
+    ${rm} -f "${lockfile}"
     ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
     ${logger} -t "${script}" "${severity}: ${message}"
 {% if (openntpd_monitor_mail_state is match('true|yes|enable')) %}
