ntp: Add support for OS family 'OpenBSD'

diff --git a/ntp/templates/default/ntp_update-time.sh.j2 b/ntp/templates/default/ntp_update-time.sh.j2
--- a/ntp/templates/default/ntp_update-time.sh.j2
+++ b/ntp/templates/default/ntp_update-time.sh.j2
@@ -31,25 +31,25 @@
 #-------------------------------------------------------------------------------
 
 SHELL='/bin/sh'
-PATH='/sbin:/bin:/usr/sbin:/usr/bin'
+PATH='/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin'
 
 #-------------------------------------------------------------------------------
 # COMMANDS
 #-------------------------------------------------------------------------------
 
-which='/usr/bin/which' && [ -x $which ] || { echo "Error: Command 'which' not found. Code: 1100"; exit 127; }
-basename=$($which basename) || { echo "Error: Command 'basename' not found. Code: 1101"; exit 127; }
-date=$($which date) || { echo "Error: Command 'date' not found. Code: 1102"; exit 127; }
-echo=$($which echo) || { echo "Error: Command 'echo' not found. Code: 1103"; exit 127; }
-expr=$($which expr) || { echo "Error: Command 'expr' not found. Code: 1104"; exit 127; }
-hostname=$($which hostname) || { echo "Error: Command 'hostname' not found. Code: 1105"; exit 127; }
-logger=$($which logger) || { echo "Error: Command 'logger' not found. Code: 1106"; exit 127; }
+which='/usr/bin/which' && [ -x $which ] || { echo "Error: Command 'which' not found."; exit 127; }
+basename=$($which basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+date=$($which date) || { echo "Error: Command 'date' not found."; exit 127; }
+echo=$($which echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+expr=$($which expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+hostname=$($which hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+logger=$($which logger) || { echo "Error: Command 'logger' not found."; exit 127; }
 {% if (ntp_monitor_mail_state is defined) and ((ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable')) %}
-mailx=$($which mailx) || { echo "Error: Command 'mailx' not found. Code: 1107"; exit 127; }
+mailx=$($which mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
-rm=$($which rm) || { echo "Error: Command 'rm' not found. Code: 1108"; exit 127; }
-touch=$($which touch) || { echo "Error: Command 'touch' not found. Code: 1109"; exit 127; }
-whoami=$($which whoami) || { echo "Error: Command 'whoami' not found. Code: 1110"; exit 127; }
+rm=$($which rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+touch=$($which touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+whoami=$($which whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
 # NTP command
 ntp_command='{{ntp_command}}'
@@ -59,10 +59,10 @@ ntp_command='{{ntp_command}}'
 #-------------------------------------------------------------------------------
 
 # Get the short host name
-host=$($hostname -s) || { echo "Error: Host name unknown. Code: 1200"; exit 68; }
+host=$($hostname -s) || { echo "Error: Host name unknown."; exit 68; }
 
 # Get the script name and PID
-script="$($basename $0)[$$]" || { echo "Error: Command invoked cannot execute. Code: 1201"; exit 126; }
+script="$($basename $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
 
 # Get the start date and time
 date_start=$($date '+%Y-%m-%dT%H:%M:%S%z')
@@ -78,9 +78,6 @@ lockfile='{{file_path_ntp_script_dir}}/ntp_update-time.lock'
 
 # Set the initial return value
 retval=0
-
-# Set the initial exit code
-code='0000'
 
 # Define the initial log severity
 severity='Debug'
@@ -126,9 +123,8 @@ mail_subject='NTP: Update Time - Error ({{ansible_hostname}})'
 # Mail monitoring
 mail_error() {
   retval=$1
-  code=$2
-  severity=$3
-  message=$4
+  severity=$2
+  message=$3
   # Define the mail body
   mail_body="--------------------------------------------------------------------------------
 ERROR
@@ -136,7 +132,6 @@ ERROR
 
 Message     : $message
 Severity    : $severity
-Code        : $code
 Date & Time : $($date '+%Y-%m-%dT%H:%M:%S%z')
 
 --------------------------------------------------------------------------------
@@ -187,51 +182,83 @@ Subject     : $mail_subject"
 }
 {% endif %}
 
+# Check if script is running as correct user
+check_script_user() {
+  if [ "$($whoami)" != "$user" ]; then
+    retval=77
+    severity='Error'
+    message="Please run script as user '$user'"
+    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message""
+    exit $retval
+  fi
+}
+
+# Create lockfile
+create_lockfile() {
+  if [ ! -e $lockfile ]; then
+    $touch $lockfile || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  else
+    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
+  fi
+}
+
+# Remove lockfile
+remove_lockfile() {
+  if [ -e $lockfile ]; then
+    $rm -f $lockfile || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+  else
+    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
+  fi
+}
+
 # Log and exit if return value is not equal zero
 log_and_exit_on_error() {
   retval=$1
-  code=$2
-  severity=$3
-  message=$4
+  severity=$2
+  message=$3
   if [ $retval -ne 0 ]; then
     $rm -f $lockfile
-    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
-    $logger -t $script "$severity: $message Code: $code"
+    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message""
+    $logger -t $script "$severity: $message"
 {% if (ntp_monitor_mail_state is defined) and ((ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable')) %}
-    mail_error $retval $code "$severity" "$message"
+    mail_error $retval "$severity" "$message"
 {% endif %}
     exit $retval
   fi
 }
 
-#-------------------------------------------------------------------------------
-# CHECKS
-#-------------------------------------------------------------------------------
+# Log and exit
+log_and_exit() {
+  # Get the end date and time
+  date_end=$($date '+%Y-%m-%dT%H:%M:%S%z')
 
-# Check if script is running as correct user
-if [ "$($whoami)" != "$user" ]; then
-  retval=77
-  code='1300'
-  severity='Error'
-  message="Please run script as user '$user'"
-  $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
+  # Get the end time (seconds since 1970-01-01T00:00:00+00:00)
+  time_end=$($date '+%s')
+
+  # Calculate execution time
+  time_exec=$($expr $time_end - $time_start)
+
+  # Convert execution time into human readable format
+  time_hr=$($date -u -r "$time_exec" '+%H:%M:%S')
+
+  # Logging and alerting
+  retval=0
+  severity='Info'
+  message='System time and hardware clock updated.'
+  $logger -t $script "$severity: $message Duration: $time_hr"
+
   exit $retval
-fi
-
-#-------------------------------------------------------------------------------
-# LOCKFILE
-#-------------------------------------------------------------------------------
-
-# Create lockfile
-if [ ! -e $lockfile ]; then
-  $touch $lockfile || log_and_exit_on_error "$?" '1400' 'Warning' 'Could not create lockfile. Please investigate.'
-else
-  log_and_exit_on_error "$?" '1401' 'Warning' 'Lockfile does already exist. Please investigate.'
-fi
+}
 
 #-------------------------------------------------------------------------------
 # SCRIPT
 #-------------------------------------------------------------------------------
+
+# Check if script is running as correct user
+check_script_user
+
+# Create lockfile
+create_lockfile
 
 # Update the system time by polling NTP servers to determine the correct time
 for ntp_server in $ntp_servers ; do
@@ -243,40 +270,10 @@ for ntp_server in $ntp_servers ; do
     ntp_status=1
   fi
 done
-log_and_exit_on_error "$ntp_status" '1500' 'Error' 'Unable to update the system time.'
+log_and_exit_on_error "$ntp_status" 'Error' 'Unable to update the system time.'
 
-#-------------------------------------------------------------------------------
-# LOCKFILE
-#-------------------------------------------------------------------------------
+# Remove lockfile
+remove_lockfile
 
-# Delete lockfile
-if [ -e $lockfile ]; then
-  $rm -f $lockfile || log_and_exit_on_error "$?" '1402' 'Warning' 'Could not delete lockfile. Please investigate.'
-else
-  log_and_exit_on_error "$?" '1403' 'Warning' 'Lockfile did not exist. Please investigate.'
-fi
-
-#-------------------------------------------------------------------------------
-# LOGGING
-#-------------------------------------------------------------------------------
-
-# Get the end date and time
-date_end=$($date '+%Y-%m-%dT%H:%M:%S%z')
-
-# Get the end time (seconds since 1970-01-01T00:00:00+00:00)
-time_end=$($date '+%s')
-
-# Calculate execution time
-time_exec=$($expr $time_end - $time_start)
-
-# Convert execution time into human readable format
-time_hr=$($date -u -r "$time_exec" '+%H:%M:%S')
-
-# Logging and alerting
-retval=0
-code='0000'
-severity='Info'
-message='System time and hardware clock updated.'
-$logger -t $script "$severity: $message Duration: $time_hr"
-
-exit $retval
+# Log and exit
+log_and_exit
