zfs: Minor script improvements

diff --git a/zfs/templates/default/zfs_scrub-pools.sh.j2 b/zfs/templates/default/zfs_scrub-pools.sh.j2
--- a/zfs/templates/default/zfs_scrub-pools.sh.j2
+++ b/zfs/templates/default/zfs_scrub-pools.sh.j2
@@ -37,32 +37,32 @@ PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 # COMMANDS
 #-------------------------------------------------------------------------------
 
-which='/usr/bin/which' && [ -x $which ] || { echo "Error: Command 'which' not found. Code: 1100"; exit 127; }
-basename=$($which basename) || { echo "Error: Command 'basename' not found. Code: 1101"; exit 127; }
-date=$($which date) || { echo "Error: Command 'date' not found. Code: 1102"; exit 127; }
-echo=$($which echo) || { echo "Error: Command 'echo' not found. Code: 1103"; exit 127; }
-expr=$($which expr) || { echo "Error: Command 'expr' not found. Code: 1104"; exit 127; }
-grep=$($which grep) || { echo "Error: Command 'grep' not found. Code: 1105"; exit 127; }
-hostname=$($which hostname) || { echo "Error: Command 'hostname' not found. Code: 1106"; exit 127; }
-logger=$($which logger) || { echo "Error: Command 'logger' not found. Code: 1107"; exit 127; }
+which='/usr/bin/which' && [ -x $which ] || { echo "Error: Command 'which' not found."; exit 127; }
+basename=$($which basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+date=$($which date) || { echo "Error: Command 'date' not found."; exit 127; }
+echo=$($which echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+expr=$($which expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+grep=$($which grep) || { echo "Error: Command 'grep' not found."; exit 127; }
+hostname=$($which hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+logger=$($which logger) || { echo "Error: Command 'logger' not found."; exit 127; }
 {% if (zfs_monitor_mail_state is defined) and ((zfs_monitor_mail_state == 'true') or (zfs_monitor_mail_state == 'yes') or (zfs_monitor_mail_state == 'enable')) %}
-mailx=$($which mailx) || { echo "Error: Command 'mailx' not found. Code: 1108"; exit 127; }
+mailx=$($which mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
-rm=$($which rm) || { echo "Error: Command 'rm' not found. Code: 1109"; exit 127; }
-sleep=$($which sleep) || { echo "Error: Command 'sleep' not found. Code: 1110"; exit 127; }
-touch=$($which touch) || { echo "Error: Command 'touch' not found. Code: 1111"; exit 127; }
-whoami=$($which whoami) || { echo "Error: Command 'whoami' not found. Code: 1112"; exit 127; }
-zpool=$($which zpool) || { echo "Error: Command 'zpool' not found. Code: 1113"; exit 127; }
+rm=$($which rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+sleep=$($which sleep) || { echo "Error: Command 'sleep' not found."; exit 127; }
+touch=$($which touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+whoami=$($which whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+zpool=$($which zpool) || { echo "Error: Command 'zpool' not found."; exit 127; }
 
 #-------------------------------------------------------------------------------
 # VARIABLES
 #-------------------------------------------------------------------------------
 
 # Get the short host name
-host=$($hostname -s) || { echo "Error: Host name unknown. Code: 1200"; exit 68; }
+host=$($hostname -s) || { echo "Error: Host name unknown."; exit 68; }
 
 # Get the script name and PID
-script="$($basename $0)[$$]" || { echo "Error: Command invoked cannot execute. Code: 1201"; exit 126; }
+script="$($basename $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
 
 # Get the start date and time
 date_start=$($date '+%Y-%m-%dT%H:%M:%S%z')
@@ -78,9 +78,6 @@ lockfile='{{file_path_zfs_script_dir}}/zfs_scrub-pools.lock'
 
 # Set the initial return value
 retval=0
-
-# Set the initial exit code
-code='0000'
 
 # Define the initial log severity
 severity='Debug'
@@ -125,9 +122,8 @@ mail_subject='ZFS: Scrub Pool - Error ({{ansible_hostname}})'
 # Mail monitoring
 mail_error() {
   retval=$1
-  code=$2
-  severity=$3
-  message=$4
+  severity=$2
+  message=$3
   # Define the mail body
   mail_body="--------------------------------------------------------------------------------
 ERROR
@@ -135,7 +131,6 @@ ERROR
 
 Message     : $message
 Severity    : $severity
-Code        : $code
 Date & Time : $($date '+%Y-%m-%dT%H:%M:%S%z')
 
 --------------------------------------------------------------------------------
@@ -186,25 +181,8 @@ Subject     : $mail_subject"
 }
 {% endif %}
 
-# Log and exit if return value is not equal zero
-log_and_exit_on_error() {
-  retval=$1
-  code=$2
-  severity=$3
-  message=$4
-  if [ $retval -ne 0 ]; then
-    $rm -f $lockfile
-    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
-    $logger -t $script "$severity: $message Code: $code"
-{% if (zfs_monitor_mail_state is defined) and ((zfs_monitor_mail_state == 'true') or (zfs_monitor_mail_state == 'yes') or (zfs_monitor_mail_state == 'enable')) %}
-    mail_error $retval $code "$severity" "$message"
-{% endif %}
-    exit $retval
-  fi
-}
-
-# Watch and wait on change
-watch_and_wait_on_change() {
+# Watch and wait for change
+watch_and_wait_for_change() {
   watch_key=$1
   watch_value=$2
   watch_option=$3
@@ -220,93 +198,112 @@ watch_and_wait_on_change() {
   done
 }
 
-#-------------------------------------------------------------------------------
-# CHECKS
-#-------------------------------------------------------------------------------
-
 # Check if script is running as correct user
-if [ "$($whoami)" != "$user" ]; then
-  retval=77
-  code='1300'
-  severity='Error'
-  message="Please run script as user '$user'"
-  $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
-  exit $retval
-fi
-
-#-------------------------------------------------------------------------------
-# LOCKFILE
-#-------------------------------------------------------------------------------
+check_script_user() {
+  if [ "$($whoami)" != "$user" ]; then
+    retval=77
+    severity='Error'
+    message="Please run script as user '$user'"
+    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message""
+    exit $retval
+  fi
+}
 
 # Create lockfile
-if [ ! -e $lockfile ]; then
-  $touch $lockfile || log_and_exit_on_error "$?" '1400' 'Warning' 'Could not create lockfile. Please investigate.'
-else
-  log_and_exit_on_error "$?" '1401' 'Warning' 'Lockfile does already exist. Please investigate.'
-fi
+create_lockfile() {
+  if [ ! -e $lockfile ]; then
+    $touch $lockfile || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  else
+    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
+  fi
+}
+
+# Remove lockfile
+remove_lockfile() {
+  if [ -e $lockfile ]; then
+    $rm -f $lockfile || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
+  else
+    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
+  fi
+}
+
+# Log and exit if return value is not equal zero
+log_and_exit_on_error() {
+  retval=$1
+  severity=$2
+  message=$3
+  if [ $retval -ne 0 ]; then
+    $rm -f $lockfile
+    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message""
+    $logger -t $script "$severity: $message"
+{% if (zfs_monitor_mail_state is defined) and ((zfs_monitor_mail_state == 'true') or (zfs_monitor_mail_state == 'yes') or (zfs_monitor_mail_state == 'enable')) %}
+    mail_error $retval "$severity" "$message"
+{% endif %}
+    exit $retval
+  fi
+}
+
+# Log and exit
+log_and_exit() {
+  # Get the end date and time
+  date_end=$($date '+%Y-%m-%dT%H:%M:%S%z')
+
+  # Get the end time (seconds since 1970-01-01T00:00:00+00:00)
+  time_end=$($date '+%s')
+
+  # Calculate execution time
+  time_exec=$($expr $time_end - $time_start)
+
+  # Convert execution time into human readable format
+  time_hr=$($date -u -r "$time_exec" '+%H:%M:%S')
+
+  # Logging and alerting
+  retval=0
+  severity='Info'
+  message='All ZFS pools are healthy.'
+  $logger -t $script "$severity: $message Duration: $time_hr"
+
+  exit $retval
+}
 
 #-------------------------------------------------------------------------------
 # SCRIPT
 #-------------------------------------------------------------------------------
 
+# Check if script is running as correct user
+check_script_user
+
+# Create lockfile
+create_lockfile
+
 # Scrub ZFS pools
 for pool in $zfs_pools ; do
   # Wait until previous scrub has finished
   time_initial=0
-  watch_and_wait_on_change "$zpool status" 'scrub in progress' '' '5' '300'
+  watch_and_wait_for_change "$zpool status" 'scrub in progress' '' '5' '300'
 
   # Scrub next ZFS pool
   $zpool scrub $pool
-  log_and_exit_on_error "$?" '1500' 'Error' "Unable to scrub ZFS pool: '$pool'"
+  log_and_exit_on_error "$?" 'Error' "Unable to scrub ZFS pool: '$pool'"
 done
 
 # Check ZFS pools
 for pool in $zfs_pools ; do
   # Wait until previous scrub has finished
   time_initial=0
-  watch_and_wait_on_change "$zpool status" 'scrub in progress' '' '5' '300'
+  watch_and_wait_for_change "$zpool status" 'scrub in progress' '' '5' '300'
 
   # Get next ZFS pool status
   zfs_pool_status="$($zpool status -xv $pool)"
-  log_and_exit_on_error "$?" '1501' 'Error' "Unable to get ZFS pool status: '$pool'"
+  log_and_exit_on_error "$?" 'Error' "Unable to get ZFS pool status: '$pool'"
 
   # Check next ZFS pool status
   echo "$zfs_pool_status" | $grep 'healthy' > /dev/null 2>&1
-  log_and_exit_on_error "$?" '1502' 'Critical' "ZFS pool is unhealthy: '$pool'"
+  log_and_exit_on_error "$?" 'Critical' "ZFS pool is unhealthy: '$pool'"
 done
 
-#-------------------------------------------------------------------------------
-# LOCKFILE
-#-------------------------------------------------------------------------------
+# Remove lockfile
+remove_lockfile
 
-# Delete lockfile
-if [ -e $lockfile ]; then
-  $rm -f $lockfile || log_and_exit_on_error "$?" '1402' 'Warning' 'Could not delete lockfile. Please investigate.'
-else
-  log_and_exit_on_error "$?" '1403' 'Warning' 'Lockfile did not exist. Please investigate.'
-fi
-
-#-------------------------------------------------------------------------------
-# LOGGING
-#-------------------------------------------------------------------------------
-
-# Get the end date and time
-date_end=$($date '+%Y-%m-%dT%H:%M:%S%z')
-
-# Get the end time (seconds since 1970-01-01T00:00:00+00:00)
-time_end=$($date '+%s')
-
-# Calculate execution time
-time_exec=$($expr $time_end - $time_start)
-
-# Convert execution time into human readable format
-time_hr=$($date -u -r "$time_exec" '+%H:%M:%S')
-
-# Logging and alerting
-retval=0
-code='0000'
-severity='Info'
-message='All ZFS pools are healthy.'
-$logger -t $script "$severity: $message Duration: $time_hr"
-
-exit $retval
+# Log and exit
+log_and_exit
