Add mail monitoring options and improve script overall

diff --git a/ntp/templates/main/ntp_update-time.bash.j2 b/ntp/templates/main/ntp_update-time.bash.j2
--- a/ntp/templates/main/ntp_update-time.bash.j2
+++ b/ntp/templates/main/ntp_update-time.bash.j2
@@ -39,24 +39,27 @@ PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
 which='/usr/bin/which'
 
-basename=$($which basename) || exit 1
-hwclock=$($which hwclock) || exit 1
-date=$($which date) || exit 1
-echo=$($which echo) || exit 1
-expr=$($which expr) || exit 1
-hostname=$($which hostname) || exit 1
-logger=$($which logger) || exit 1
-rm=$($which rm) || exit 1
-touch=$($which touch) || exit 1
-whoami=$($which whoami) || exit 1
+basename=$($which basename) || exit 0100
+hwclock=$($which hwclock) || exit 0101
+date=$($which date) || exit 0102
+echo=$($which echo) || exit 0103
+expr=$($which expr) || exit 0104
+hostname=$($which hostname) || exit 0105
+logger=$($which logger) || exit 0106
+{% if (ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable') %}
+mailx=$($which mailx) || exit 0107
+{% endif %}
+rm=$($which rm) || exit 0108
+touch=$($which touch) || exit 0109
+whoami=$($which whoami) || exit 0110
 
 # Determine available NTP command
 if [ -x "$($which sntp 2> /dev/null)" ]; then
-  ntp='sntp --settod --syslog'
+  ntp_command='sntp --settod --syslog'
 elif [ -x "$($which ntpdate 2> /dev/null)" ]; then
-  ntp='ntpdate -s'
+  ntp_command='ntpdate -s'
 else
-  exit 1
+  exit 0111
 fi
 
 #-------------------------------------------------------------------------------
@@ -70,7 +73,7 @@ host=$($hostname -s)
 script="$($basename $0)[$$]"
 
 # Get start date and time
-date_start=$($date '+%Y-%m-%d %H:%M:%S')
+date_start=$($date '+%Y-%m-%dT%H:%M:%S%:z')
 
 # Get start instant (seconds since 1970-01-01 00:00:00 UTC)
 instant_start=$($date '+%s')
@@ -84,6 +87,9 @@ lockfile='{{file_path_ntp_script_dir}}/ntp_update-time.lock'
 # Set initial return value
 retval='0'
 
+# Set initial exit code
+code='0000'
+
 # Set initial log severity
 severity='Debug'
 
@@ -93,19 +99,95 @@ message='Please check log files for more information.'
 # List of NTP servers
 ntp_servers='{% if not ((ntp_server == None) or (ntp_server == '') or (ntp_server == [])) %}{% for server in ntp_server %}{{server}} {% endfor %}{% else %}ntp.{{ansible_domain}}{% endif %}'
 
+{% if (ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable') %}
+# Define the mail sender
+mail_sender='{% if not ((ntp_monitor_mail_sender == None) or (ntp_monitor_mail_sender == '')) %}{{ntp_monitor_mail_sender}}{% else %}root@{{ansible_domain}}{% endif %}'
+
+# Define the mail recipient
+mail_recipient='{% if not ((ntp_monitor_mail_recipient == None) or (ntp_monitor_mail_recipient == '') or (ntp_monitor_mail_recipient == [])) %}{% for mail_recipient in ntp_monitor_mail_recipient %}{{mail_recipient}},{% endfor %}{% else %}admin@{{ansible_domain}}{% endif %}'
+
+# Define the mail subject
+mail_subject='{% if not ((ntp_monitor_mail_subject == None) or (ntp_monitor_mail_subject == '')) %}{{ntp_monitor_mail_subject}}{% else %}"{{ansible_hostname}}: NTP - Update Time - Error"{% endif %}'
+{% endif %}
+
 #-------------------------------------------------------------------------------
 # FUNCTIONS
 #-------------------------------------------------------------------------------
 
+{% if (ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable') %}
+# Mail monitoring
+mail_error () {
+  retval=$1
+  code=$2
+  severity=$3
+  message=$4
+  # Define the mail body
+  mail_body="--------------------------------------------------------------------------------
+$mail_subject
+--------------------------------------------------------------------------------
+
+--------------------------------------------------------------------------------
+SYSTEM
+--------------------------------------------------------------------------------
+
+Hostname    : {{ansible_hostname}}
+FQDN        : {{ansible_fqdn}}
+
+--------------------------------------------------------------------------------
+ERROR
+--------------------------------------------------------------------------------
+
+Message     : $message
+Severity    : $severity
+Code        : $code
+Date & Time : $($date '+%Y-%m-%dT%H:%M:%S%:z')
+
+--------------------------------------------------------------------------------
+SCRIPT
+--------------------------------------------------------------------------------
+
+Name        : ntp_update-time.bash
+Type        : bash script
+PID         : $$
+
+--------------------------------------------------------------------------------
+OPERATING SYSTEM
+--------------------------------------------------------------------------------
+
+Type        : {{ansible_system}}
+Family      : {{ansible_os_family}}
+Distribution: {{ansible_distribution}}
+Version     : {{ansible_distribution_version}}
+Architecture: {{ansible_architecture}}
+
+--------------------------------------------------------------------------------
+KERNEL
+--------------------------------------------------------------------------------
+
+Type        : {{ansible_system}}
+Version     : {{ansible_kernel}}
+
+--------------------------------------------------------------------------------
+$script: $($date '+%Y-%m-%dT%H:%M:%S%:z')
+--------------------------------------------------------------------------------"
+
+  $echo "$mail_body" | $mailx -r "$mail_sender" -s "$mail_subject" "$mail_recipient" > /dev/null 2>&1
+}
+{% endif %}
+
 # Log and exit if return value is not equal zero
 log_and_exit_if_error () {
   retval=$1
-  severity=$2
-  message=$3
+  code=$2
+  severity=$3
+  message=$4
   if [ "$retval" -ne '0' ]; then
     $rm -f $lockfile
-    $echo "$($date '+%Y-%m-%dT%H:%M:%S%:z') - $host - $script: "$severity: $message""
-    $logger -t $script "$severity: $message"
+    $echo "$($date '+%Y-%m-%dT%H:%M:%S%:z') - $host - $script: "$severity "($code)": $message""
+    $logger -t $script "$severity '($code)': $message"
+{% if (ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable') %}
+    mail_error "$retval" "$code" "$severity" "$message"
+{% endif %}
     exit $retval
   fi
 }
@@ -116,10 +198,11 @@ log_and_exit_if_error () {
 
 # Check if script is running as correct user
 if [ "$($whoami)" != "$user" ]; then
+  code='0200'
   severity='Error'
   message="Please run script as user '$user'"
-  $echo "$($date '+%Y-%m-%dT%H:%M:%S%:z') - $host - $script: "$severity: $message""
-  exit 1
+  $echo "$($date '+%Y-%m-%dT%H:%M:%S%:z') - $host - $script: "$severity "($code)": $message""
+  exit $code
 fi
 
 #-------------------------------------------------------------------------------
@@ -128,9 +211,9 @@ fi
 
 # Create lockfile
 if [ ! -e $lockfile ]; then
-  $touch $lockfile || log_and_exit_if_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
+  $touch $lockfile || log_and_exit_if_error "$?" '0300' 'Warning' 'Could not create lockfile. Please investigate.'
 else
-  log_and_exit_if_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
+  log_and_exit_if_error "$?" '0301' 'Warning' 'Lockfile does already exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -139,13 +222,13 @@ fi
 
 # Update the system time by polling NTP servers to determine the correct time
 for ntp_server in $ntp_servers ; do
-  $ntp $ntp_server > /dev/null 2>&1
-  log_and_exit_if_error "$?" 'Error' 'Unable to update the system time.'
+  $ntp_command $ntp_server > /dev/null 2>&1
+  log_and_exit_if_error "$?" '0400' 'Error' 'Unable to update the system time.'
 done
 
 # Update the hardware clock to the system time
 $hwclock -w
-log_and_exit_if_error "$?" 'Error' 'Unable to update the hardware clock.'
+log_and_exit_if_error "$?" '0401' 'Error' 'Unable to update the hardware clock.'
 
 #-------------------------------------------------------------------------------
 # LOCKFILE
@@ -153,9 +236,9 @@ log_and_exit_if_error "$?" 'Error' 'Unable to update the hardware clock.'
 
 # Delete lockfile
 if [ -e $lockfile ]; then
-  $rm -f $lockfile || log_and_exit_if_error "$?" 'Warning' 'Could not delete lockfile. Please investigate.'
+  $rm -f $lockfile || log_and_exit_if_error "$?" '0302' 'Warning' 'Could not delete lockfile. Please investigate.'
 else
-  log_and_exit_if_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
+  log_and_exit_if_error "$?" '0304' 'Warning' 'Lockfile did not exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -163,7 +246,7 @@ fi
 #-------------------------------------------------------------------------------
 
 # Get end date and time
-date_end=$($date '+%Y-%m-%d %H:%M:%S')
+date_end=$($date '+%Y-%m-%dT%H:%M:%S%:z')
 
 # Get end instant (seconds since 1970-01-01 00:00:00 UTC)
 instant_end=$($date '+%s')
@@ -176,6 +259,7 @@ exec_time=$($date -d "1970-01-01 $exec_calc sec" '+%H:%M:%S')
 
 # Logging and alerting
 retval='0'
+code='0000'
 severity='Informational'
 message='System time and hardware clock updated.'
 $logger -t $script "$severity: $message"
