ntp: Add support for OS family 'FreeBSD'

diff --git a/ntp/templates/main/ntp_update-time.sh.j2 b/ntp/templates/main/ntp_update-time.sh.j2
--- a/ntp/templates/main/ntp_update-time.sh.j2
+++ b/ntp/templates/main/ntp_update-time.sh.j2
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env sh
 
 #-------------------------------------------------------------------------------
 #                             ANSIBLE MANAGED FILE
@@ -9,8 +9,8 @@
 #-------------------------------------------------------------------------------
 #        o
 #    ____|____
-#   |         |  Name   : ntp_update-time.bash
-#   |  _   _  |  Type   : bash script
+#   |         |  Name   : ntp_update-time.sh
+#   |  _   _  |  Type   : shell script
 #   | [_] [_] |  Role   : ntp
 #   |____~____|
 #    ___//__//   Authors: robomon community
@@ -30,16 +30,18 @@
 # SHELL VARIABLES
 #-------------------------------------------------------------------------------
 
-SHELL='/bin/bash'
+SHELL='/bin/sh'
 PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
 #-------------------------------------------------------------------------------
 # COMMANDS
 #-------------------------------------------------------------------------------
 
-which='/usr/bin/which' && [[ -x $which ]] || exit 0100
+which='/usr/bin/which' && [ -x $which ] || exit 0100
 basename=$($which basename) || exit 0101
+{% if (ansible_os_family == 'Gentoo') %}
 hwclock=$($which hwclock) || exit 0102
+{% endif %}
 date=$($which date) || exit 0103
 echo=$($which echo) || exit 0104
 expr=$($which expr) || exit 0105
@@ -52,14 +54,8 @@ rm=$($which rm) || exit 0109
 touch=$($which touch) || exit 0110
 whoami=$($which whoami) || exit 0111
 
-# Determine available NTP command
-if [ -x "$($which sntp 2> /dev/null)" ]; then
-  ntp_command='sntp --settod --syslog'
-elif [ -x "$($which ntpdate 2> /dev/null)" ]; then
-  ntp_command='ntpdate -s -b'
-else
-  exit 0112
-fi
+# NTP command
+ntp_command='{{ntp_command}}'
 
 #-------------------------------------------------------------------------------
 # VARIABLES
@@ -72,13 +68,13 @@ host=$($hostname -s) || exit 0200
 script="$($basename $0)[$$]" || exit 0201
 
 # Get the start date and time
-date_start=$($date '+%Y-%m-%dT%H:%M:%S%:z')
+date_start=$($date '+%Y-%m-%dT%H:%M:%S%z')
 
-# Get the start instant (seconds since 1970-01-01T00:00:00+00:00)
-instant_start=$($date '+%s')
+# Get the start time (seconds since 1970-01-01T00:00:00+00:00)
+time_start=$($date '+%s')
 
 # Define the script user
-user='{{file_owner_ntp_update_time_bash}}'
+user='{{file_owner_ntp_update_time_sh}}'
 
 # Define the lockfile location
 lockfile='{{file_path_ntp_script_dir}}/ntp_update-time.lock'
@@ -96,17 +92,17 @@ severity='Debug'
 message='Please check log files for more information.'
 
 # List of NTP servers
-ntp_servers='{% if (ntp_server is defined) and not ((ntp_server == None) or (ntp_server == '') or (ntp_server == [])) %}{% for server in ntp_server %}{{server}} {% endfor %}{% else %}ntp.{{ansible_domain}}{% endif %}'
+ntp_servers='{% if (ntp_config is defined) and not ((ntp_config == None) or (ntp_config == '') or (ntp_config == [])) %}{% for config in ntp_config|sort %}{% if (config.server is defined) and not ((config.server == None) or (config.server == '') or (config.server == [])) %}{% for server in config.server|sort %}{{server|e}} {% endfor %}{% endif %}{% endfor %}{% else %}ntp{% endif %}'
 
 {% if (ntp_monitor_mail_state is defined) and ((ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable')) %}
 # Define the mail sender
-mail_sender='{% if (ntp_monitor_mail_sender is defined) and not ((ntp_monitor_mail_sender == None) or (ntp_monitor_mail_sender == '')) %}{{ntp_monitor_mail_sender}}{% else %}root@{{ansible_domain}}{% endif %}'
+mail_sender='{% if (ntp_monitor_mail_sender is defined) and not ((ntp_monitor_mail_sender == None) or (ntp_monitor_mail_sender == '')) %}{{ntp_monitor_mail_sender|e}}{% else %}root@{{ansible_domain}}{% endif %}'
 
 # Define the mail recipient
-mail_recipient='{% if (ntp_monitor_mail_recipient is defined) and not ((ntp_monitor_mail_recipient == None) or (ntp_monitor_mail_recipient == '') or (ntp_monitor_mail_recipient == [])) %}{% for mail_recipient in ntp_monitor_mail_recipient %}{{mail_recipient}},{% endfor %}{% else %}admin@{{ansible_domain}}{% endif %}'
+mail_recipient='{% if (ntp_monitor_mail_recipient is defined) and not ((ntp_monitor_mail_recipient == None) or (ntp_monitor_mail_recipient == '') or (ntp_monitor_mail_recipient == [])) %}{% for mail_recipient in ntp_monitor_mail_recipient %}{{mail_recipient|e}}{% if not loop.last %},{% endif %}{% endfor %}{% else %}ntp{% endif %}'
 
 # Define the mail subject
-mail_subject='{% if (ntp_monitor_mail_subject is defined) and not ((ntp_monitor_mail_subject == None) or (ntp_monitor_mail_subject == '')) %}{{ntp_monitor_mail_subject}}{% else %}NTP: Update Time - Error ({{ansible_hostname}}){% endif %}'
+mail_subject='{% if (ntp_monitor_mail_subject is defined) and not ((ntp_monitor_mail_subject == None) or (ntp_monitor_mail_subject == '')) %}{{ntp_monitor_mail_subject|e}}{% else %}NTP: Update Time - Error ({{ansible_hostname}}){% endif %}'
 {% endif %}
 
 #-------------------------------------------------------------------------------
@@ -128,14 +124,14 @@ ERROR
 Message     : $message
 Severity    : $severity
 Code        : $code
-Date & Time : $($date '+%Y-%m-%dT%H:%M:%S%:z')
+Date & Time : $($date '+%Y-%m-%dT%H:%M:%S%z')
 
 --------------------------------------------------------------------------------
 SCRIPT
 --------------------------------------------------------------------------------
 
-Name        : ntp_update-time.bash
-Type        : bash script
+Name        : ntp_update-time.sh
+Type        : sh script
 PID         : $$
 
 --------------------------------------------------------------------------------
@@ -170,23 +166,23 @@ Sender      : $mail_sender
 Recipient   : $mail_recipient
 Subject     : $mail_subject"
 
-{% if (ansible_os_family == 'Gentoo') %}
-  $echo "$mail_body" | $mailx -a "From: "$mail_sender"" -s "$mail_subject" "$mail_recipient" > /dev/null 2>&1
+{% if (ansible_os_family == 'FreeBSD') %}
+  $echo "$mail_body" | $mailx -s "$mail_subject" -F "$mail_recipient" > /dev/null 2>&1
 {% else %}
-  $echo "$mail_body" | $mailx -r "$mail_sender" -s "$mail_subject" "$mail_recipient" > /dev/null 2>&1
+  $echo "$mail_body" | $mailx -a "From: "$mail_sender"" -s "$mail_subject" "$mail_recipient" > /dev/null 2>&1
 {% endif %}
 }
 {% endif %}
 
 # Log and exit if return value is not equal zero
-log_and_exit_if_error () {
+log_and_exit_on_error () {
   retval=$1
   code=$2
   severity=$3
   message=$4
   if [ $retval -ne 0 ]; then
     $rm -f $lockfile
-    $echo "$($date '+%Y-%m-%dT%H:%M:%S%:z') - $host - $script: "$severity: $code - $message""
+    $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $code - $message""
     $logger -t $script "$severity: $code - $message"
 {% if (ntp_monitor_mail_state is defined) and ((ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable')) %}
     mail_error $retval $code "$severity" "$message"
@@ -204,7 +200,7 @@ if [ "$($whoami)" != "$user" ]; then
   code='0300'
   severity='Error'
   message="Please run script as user '$user'"
-  $echo "$($date '+%Y-%m-%dT%H:%M:%S%:z') - $host - $script: "$severity "($code)": $message""
+  $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity "($code)": $message""
   exit $code
 fi
 
@@ -214,9 +210,9 @@ fi
 
 # Create lockfile
 if [ ! -e $lockfile ]; then
-  $touch $lockfile || log_and_exit_if_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
+  $touch $lockfile || log_and_exit_on_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
 else
-  log_and_exit_if_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
+  log_and_exit_on_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -226,12 +222,14 @@ fi
 # Update the system time by polling NTP servers to determine the correct time
 for ntp_server in $ntp_servers ; do
   $ntp_command $ntp_server > /dev/null 2>&1
-  log_and_exit_if_error "$?" '0500' 'Error' 'Unable to update the system time.'
+  log_and_exit_on_error "$?" '0500' 'Error' 'Unable to update the system time.'
 done
 
+{% if (ansible_os_family == 'Gentoo') %}
 # Update the hardware clock to the system time
 $hwclock -w
-log_and_exit_if_error "$?" '0501' 'Error' 'Unable to update the hardware clock.'
+log_and_exit_on_error "$?" '0501' 'Error' 'Unable to update the hardware clock.'
+{% endif %}
 
 #-------------------------------------------------------------------------------
 # LOCKFILE
@@ -239,9 +237,9 @@ log_and_exit_if_error "$?" '0501' 'Error' 'Unable to update the hardware clock.'
 
 # Delete lockfile
 if [ -e $lockfile ]; then
-  $rm -f $lockfile || log_and_exit_if_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
+  $rm -f $lockfile || log_and_exit_on_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
 else
-  log_and_exit_if_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
+  log_and_exit_on_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -249,23 +247,27 @@ fi
 #-------------------------------------------------------------------------------
 
 # Get the end date and time
-date_end=$($date '+%Y-%m-%dT%H:%M:%S%:z')
+date_end=$($date '+%Y-%m-%dT%H:%M:%S%z')
 
-# Get the end instant (seconds since 1970-01-01T00:00:00+00:00)
-instant_end=$($date '+%s')
+# Get the end time (seconds since 1970-01-01T00:00:00+00:00)
+time_end=$($date '+%s')
 
 # Calculate execution time
-exec_calc=$($expr $instant_end - $instant_start)
+time_exec=$($expr $time_end - $time_start)
 
-# Convert execution time
-exec_time=$($date -d "1970-01-01 $exec_calc sec" '+%H:%M:%S')
+# Convert execution time into human readable format
+{% if (ansible_os_family == 'Gentoo') %}
+time_hr=$($date -d "1970-01-01 $time_exec sec" '+%H:%M:%S')
+{% else %}
+time_hr=$($date -u -r "$time_exec" '+%H:%M:%S')
+{% endif %}
 
 # Logging and alerting
 retval=0
 code='0000'
-severity='Informational'
+severity='Info:'
 message='System time and hardware clock updated.'
 $logger -t $script "$severity: $message"
-$logger -t $script "Duration: $exec_time"
+$logger -t $script "Duration: $time_hr"
 
 exit $retval
