ntp: Minor script improvements

diff --git a/ntp/templates/main/ntp_update-time.sh.j2 b/ntp/templates/main/ntp_update-time.sh.j2
--- a/ntp/templates/main/ntp_update-time.sh.j2
+++ b/ntp/templates/main/ntp_update-time.sh.j2
@@ -37,22 +37,22 @@ PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 # COMMANDS
 #-------------------------------------------------------------------------------
 
-which='/usr/bin/which' && [ -x $which ] || exit 0100
-basename=$($which basename) || exit 0101
+which='/usr/bin/which' && [ -x $which ] || exit 1100
+basename=$($which basename) || exit 1101
 {% if (ansible_os_family == 'Gentoo') %}
-hwclock=$($which hwclock) || exit 0102
+hwclock=$($which hwclock) || exit 1102
 {% endif %}
-date=$($which date) || exit 0103
-echo=$($which echo) || exit 0104
-expr=$($which expr) || exit 0105
-hostname=$($which hostname) || exit 0106
-logger=$($which logger) || exit 0107
+date=$($which date) || exit 1103
+echo=$($which echo) || exit 1104
+expr=$($which expr) || exit 1105
+hostname=$($which hostname) || exit 1106
+logger=$($which logger) || exit 1107
 {% if (ntp_monitor_mail_state is defined) and ((ntp_monitor_mail_state == 'true') or (ntp_monitor_mail_state == 'yes') or (ntp_monitor_mail_state == 'enable')) %}
-mailx=$($which mailx) || exit 0108
+mailx=$($which mailx) || exit 1108
 {% endif %}
-rm=$($which rm) || exit 0109
-touch=$($which touch) || exit 0110
-whoami=$($which whoami) || exit 0111
+rm=$($which rm) || exit 1109
+touch=$($which touch) || exit 1110
+whoami=$($which whoami) || exit 1111
 
 # NTP command
 ntp_command='{{ntp_command}}'
@@ -62,10 +62,10 @@ ntp_command='{{ntp_command}}'
 #-------------------------------------------------------------------------------
 
 # Get the short host name
-host=$($hostname -s) || exit 0200
+host=$($hostname -s) || exit 1200
 
 # Get the script name and PID
-script="$($basename $0)[$$]" || exit 0201
+script="$($basename $0)[$$]" || exit 1201
 
 # Get the start date and time
 date_start=$($date '+%Y-%m-%dT%H:%M:%S%z')
@@ -196,7 +196,7 @@ log_and_exit_on_error() {
   code=$2
   severity=$3
   message=$4
-  if [ $retval -ne 0 ] ; then
+  if [ $retval -ne 0 ]; then
     $rm -f $lockfile
     $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
     $logger -t $script "$severity: $message Code: $code"
@@ -212,8 +212,8 @@ log_and_exit_on_error() {
 #-------------------------------------------------------------------------------
 
 # Check if script is running as correct user
-if [ "$($whoami)" != "$user" ] ; then
-  code='0300'
+if [ "$($whoami)" != "$user" ]; then
+  code='1300'
   severity='Error'
   message="Please run script as user '$user'"
   $echo "$($date '+%Y-%m-%dT%H:%M:%S%z') - $host - $script: "$severity: $message Code: $code""
@@ -225,10 +225,10 @@ fi
 #-------------------------------------------------------------------------------
 
 # Create lockfile
-if [ ! -e $lockfile ] ; then
-  $touch $lockfile || log_and_exit_on_error "$?" '0400' 'Warning' 'Could not create lockfile. Please investigate.'
+if [ ! -e $lockfile ]; then
+  $touch $lockfile || log_and_exit_on_error "$?" '1400' 'Warning' 'Could not create lockfile. Please investigate.'
 else
-  log_and_exit_on_error "$?" '0401' 'Warning' 'Lockfile does already exist. Please investigate.'
+  log_and_exit_on_error "$?" '1401' 'Warning' 'Lockfile does already exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
@@ -238,13 +238,19 @@ fi
 # Update the system time by polling NTP servers to determine the correct time
 for ntp_server in $ntp_servers ; do
   $ntp_command $ntp_server > /dev/null 2>&1
-  log_and_exit_on_error "$?" '0500' 'Error' 'Unable to update the system time.'
+  if [ $? -eq 0 ]; then
+    ntp_status=0
+    break;
+  else
+    ntp_status=1
+  fi
 done
+log_and_exit_on_error "$ntp_status" '1500' 'Error' 'Unable to update the system time.'
 
 {% if (ansible_os_family == 'Gentoo') %}
 # Update the hardware clock to the system time
 $hwclock -w
-log_and_exit_on_error "$?" '0501' 'Error' 'Unable to update the hardware clock.'
+log_and_exit_on_error "$?" '1501' 'Error' 'Unable to update the hardware clock.'
 {% endif %}
 
 #-------------------------------------------------------------------------------
@@ -252,10 +258,10 @@ log_and_exit_on_error "$?" '0501' 'Error' 'Unable to update the hardware clock.'
 #-------------------------------------------------------------------------------
 
 # Delete lockfile
-if [ -e $lockfile ] ; then
-  $rm -f $lockfile || log_and_exit_on_error "$?" '0402' 'Warning' 'Could not delete lockfile. Please investigate.'
+if [ -e $lockfile ]; then
+  $rm -f $lockfile || log_and_exit_on_error "$?" '1402' 'Warning' 'Could not delete lockfile. Please investigate.'
 else
-  log_and_exit_on_error "$?" '0403' 'Warning' 'Lockfile did not exist. Please investigate.'
+  log_and_exit_on_error "$?" '1403' 'Warning' 'Lockfile did not exist. Please investigate.'
 fi
 
 #-------------------------------------------------------------------------------
